version: '3.8'

services:

  minio:
      image: docker.io/bitnami/minio:2022
      ports:
        - '9000:9000'
        - '9001:9001'
      networks:
        - minionetwork
      volumes:
        - 'minio_data:/data'
      environment:
        - MINIO_ROOT_USER=${MINIO_ROOT_USER}
        - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
        - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKET}
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7861
      - DATABASE_HOST=${DATABASE_HOSTNAME}
    restart: on-failure
  pgadmin_hairsalon:
    container_name: pgadmin_hairsalon
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=Beauty_salon
      - DB_USER=postgres
      - DB_PASSWORD=7861
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    depends_on:
      - postgres
    command: ["start-dev" ]

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  minio_data:
    driver: local
  redis:
  redis-config:

networks:
  minionetwork:
    driver: bridge
  redis-network:
