"""added rel on services users

Revision ID: 0fc28bebcdfa
Revises: b3e70b9d081b
Create Date: 2024-03-07 03:13:37.268615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc28bebcdfa'
down_revision: Union[str, None] = 'b3e70b9d081b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('services_name_key', 'services', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('services_name_key', 'services', ['name'])
    # ### end Alembic commands ###
