"""added user_id to service

Revision ID: 531c4fadcee6
Revises: d25d647f95d7
Create Date: 2024-02-12 04:16:55.415681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531c4fadcee6'
down_revision: Union[str, None] = 'd25d647f95d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'services', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'user_id')
    # ### end Alembic commands ###
