"""added rel on services users

Revision ID: 900be5a3691d
Revises: 5a01f03b702e
Create Date: 2024-03-07 02:59:33.074350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900be5a3691d'
down_revision: Union[str, None] = '5a01f03b702e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
