"""added rel on services users

Revision ID: b3e70b9d081b
Revises: 900be5a3691d
Create Date: 2024-03-07 03:12:17.490576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e70b9d081b'
down_revision: Union[str, None] = '900be5a3691d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_name_uc', 'services', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_name_uc', 'services', type_='unique')
    # ### end Alembic commands ###
